---
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    volumes:
      - ./synapse-data:/data
    ports:
      - "8008:8008"
    environment:
      - SYNAPSE_SERVER_NAME=matrix-dev
      - SYNAPSE_REPORT_STATS=yes
    healthcheck:
      test: ["CMD","curl","-i","http://localhost:8008/_matrix/client/versions"]
      interval: 10s
      timeout: 5s
      retries: 6

  element-web:
    image: vectorim/element-web:latest
    container_name: element-web
    ports:
      - "8080:80"
    volumes:
      - ./element-config.json:/app/config.json
    depends_on:
      - synapse
    restart: unless-stopped

  matterbridge:
    image: 42wim/matterbridge:latest
    container_name: matterbridge
    volumes:
      - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    env_file:
      - .env
    depends_on:
      synapse:
        condition: service_healthy
    restart: unless-stopped
